### PR TITLE
Fix path generate

### LINKED ISSUE #883: Error codes are generated with root route
Because they are not subroutes ,both '/categories/'   and  '/categories'   generate the same code in current client generator:
```java
    @jakarta.ws.rs.GET
    public io.smallrye.mutiny.Uni<List<CategoryDto>> findAll(
    );
```
If the server is implemented by Quarkus Rest, there is no problem. However, there will be problems with the routing matching of some other frameworks.

Unlike Quarkus Rest,  @GetMapping(path="/") and @GetMapping()  map to different routes in Spring Boot:

@GetMapping(path="/")  =>   http://localhost:8080/categories/

@GetMapping()                =>   http://localhost:8080/categories

Based on the above reasons, we hope  '/categories/'  will generate the following code：

```java
    @jakarta.ws.rs.GET
    @jakarta.ws.rs.Path("/")
    public io.smallrye.mutiny.Uni<List<CategoryDto>> findAll(
    );
```

### PR DESCRIPTION
**Pull request by yuhaibohotmail**
fix #883 

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [our code style](CONTRIBUTING.md#code-style)
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] Subject`
- [x] Pull Request contains link to the issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

File: client/integration-tests/path/src/main/resources/application.properties [hunk 1]
```diff
@@ -0,0 +1,3 @@
+quarkus.rest-client.quarkus_simple_openapi_yaml.url=http://localhost:8080
+
+quarkus.package.jar.decompiler.enabled=true
```
Comment (ricardozanini) [inline client/integration-tests/path/src/main/resources/application.properties:3]: Why do we need this property?

File: client/integration-tests/path/src/test/java/io/quarkiverse/openapi/generator/it/PathTest.java [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+                        .getAnnotation(Path.class)
+                        .value())
+                .isEqualTo("/{id}");
+
+        assertThat(
+                Class.forName(apiClassName)
+                        .getMethod("userResourceFindAll")
+                        .getAnnotation(Path.class)
+                        .value())
+                .isEqualTo("/");
```
Comment (ricardozanini) [inline client/integration-tests/path/src/test/java/io/quarkiverse/openapi/generator/it/PathTest.java:82]: So now, instead of `locahost:8080`, I will have `localhost:8080/`? And will it work both ways? If not, we should not force the slash in the end.

Comment (yuhaibohotmail) [reply client/integration-tests/path/src/test/java/io/quarkiverse/openapi/generator/it/PathTest.java:82]: The slash in the end is not force. instead of locahost:8080, you will have localhost:8080

It depend on openapi documents

If the document has slashes

https://github.com/quarkiverse/quarkus-openapi-generator/blob/ab24f97a192005132e1d3ee81f41fddc117ebf4f/client/integration-tests/path/src/main/openapi/openapi-path-with-forward-slash.yaml#L12

we will have slashes

https://github.com/quarkiverse/quarkus-openapi-generator/blob/ab24f97a192005132e1d3ee81f41fddc117ebf4f/client/integration-tests/path/src/test/java/io/quarkiverse/openapi/generator/it/PathTest.java#L82

If the document has no slash

https://github.com/quarkiverse/quarkus-openapi-generator/blob/ab24f97a192005132e1d3ee81f41fddc117ebf4f/client/integration-tests/path/src/main/openapi/openapi-path.yaml#L12

No path annotation generated

https://github.com/quarkiverse/quarkus-openapi-generator/blob/ab24f97a192005132e1d3ee81f41fddc117ebf4f/client/integration-tests/path/src/test/java/io/quarkiverse/openapi/generator/it/PathTest.java#L42

File: client/integration-tests/path/src/main/resources/application.properties (hunk 1 above)
Comment (yuhaibohotmail) [reply client/integration-tests/path/src/main/resources/application.properties:3]: Sorry, we don't need that. I will correct that.

**Review by hbelmiro — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Comment by hbelmiro** [comment]
@all-contributors add @yuhaibohotmail for code and test.
