### PR TITLE
Fix #933 - Filter oauth security definitions from spec when generating `CompositeAuthenticationProvider`

### LINKED ISSUE #933: Spec file with multiple flows in the `oauth` schema leads into duplicated `@OauthAuthenticationMarker` in `CompositeAuthenticationProvider`
Hi team,

we are currently trying to upgrade the Quarkus version (to `3.15.2`) in Kogito Runtimes, and after upgrading the [quarkus-openapi-generator](https://github.com/quarkiverse/quarkus-openapi-generator) to `2.7.1-lts`, we noticed that some of our IT tests were failing when the openapi spec files have multiple flows in the `oauth` Security Schema, ej: [openapi3.0-security.yaml](https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/quarkus/integration-tests/integration-tests-quarkus-openapi-client/src/main/resources/specs/openapi3.0-security.yaml)

With this setup, the extension generates the `CompositeAuthenticationProvider` with a duplicated `OauthAuthenticationMarker` annotation, which leads into the `GeneratorProcessor` trying to register twice an `AuthProvider` Synthetic Bean using the same identifier breaking the app build.

* Generated `CompositeAuthenticationProvider`:
```
@Priority(1000)
@AuthenticationMarkers({
 @OauthAuthenticationMarker(name = "oauth", openApiSpecId = "openapi3_0_security_yaml" ),
 @OauthAuthenticationMarker(name = "oauth", openApiSpecId = "openapi3_0_security_yaml" )
})
public class CompositeAuthenticationProvider implements ClientRequestFilter {
...
}
```

* Error logs when building the application

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.15.2:build (default) on project integration-tests-quarkus-openapi-client: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.SyntheticBeansProcessor#initStatic threw an exception: java.lang.IllegalStateException: A synthetic bean with identifier Wb25h6J20BU0nnvE3Cp26vFuAL8 is already registered: SYNTHETIC bean [types=[io.quarkiverse.openapi.generator.providers.AuthProvider, java.lang.Object], qualifiers=[@Any, @io.quarkiverse.openapi.generator.OpenApiSpec(openApiSpecId = "openapi3_0_security_yaml"), @io.quarkiverse.openapi.generator.AuthName(name = "oauth")], target=n/a]
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.addSyntheticBean(BeanDeployment.java:1511)
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment$BeanRegistrationContextImpl.accept(BeanDeployment.java:1866)
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment$BeanRegistrationContextImpl.accept(BeanDeployment.java:1835)
[ERROR] 	at io.quarkus.arc.processor.BeanConfigurator.done(BeanConfigurator.java:114)
[ERROR] 	at io.quarkus.arc.deployment.SyntheticBeansProcessor.configureSyntheticBean(SyntheticBeansProcessor.java:92)
[ERROR] 	at io.quarkus.arc.deployment.SyntheticBeansProcessor.initStatic(SyntheticBeansProcessor.java:39)
[ERROR] 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:840)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
[ERROR] -> [Help 1]
```

We can adjust our tests to avoid this issue, but I think it is worth it to have it reported.

### PR DESCRIPTION
**Pull request by ricardozanini**
Many thanks for submitting your Pull Request :heart:!

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [our code style](CONTRIBUTING.md#code-style)
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] Subject`
- [x] Pull Request contains link to the issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

Closes #933 

In this PR, we added a new custom Qute template function to filter OAuth methods by name since only one `CompositeAuthenticationProvider` class is required to process OIDC authentication per OAuth instance.

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-quarkus2` to backport the original PR to the `quarkus2` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

File: client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/OpenApiNamespaceResolver.java [hunk 1]
```diff
@@ -58,6 +64,26 @@ public boolean hasAuthMethods(OperationMap operations) {
...
+     * Ignore the OAuth flows by filtering every oauth instance by name. The inner openapi-generator library duplicates the
+     * OAuth instances per flow in the openapi spec.
+     * So a specification file with more than one flow defined has two entries in the list. For now, we do not use this
+     * information in runtime so it can be safely filtered and ignored.
+     *
+     * @param oauthOperations passed through the Qute template
+     * @see "resources/templates/libraries/microprofile/auth/compositeAuthenticationProvider.qute"
+     * @return The list filtered by unique auth name
+     */
+    public List<CodegenSecurity> getUniqueOAuthOperations(ArrayList<CodegenSecurity> oauthOperations) {
```
Comment (fjtirado) [inline client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/OpenApiNamespaceResolver.java:77]: I think is better, if possible, to use List rather than ArrayList

File: client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/OpenApiNamespaceResolver.java [hunk 2]
```diff
@@ -58,6 +64,26 @@ public boolean hasAuthMethods(OperationMap operations) {
...
+        if (oauthOperations != null) {
+            return oauthOperations.stream()
+                    .collect(Collectors.toMap(security -> security.name, security -> security,
+                            (existing, replacement) -> existing, LinkedHashMap::new))
+                    .values().stream().toList();
+        }
+        return Collections.emptyList();
```
Comment (fjtirado) [inline client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/OpenApiNamespaceResolver.java:84]:
```suggestion
        return oauthOperations != null  ? 
          new ArrayList<>(oauthOperations.stream()
                    .collect(Collectors.toMap(security -> security.name, security -> security,
                            (existing, replacement) -> existing, LinkedHashMap::new))
                    .values()) : Collections.emptyList();
```

File: client/deployment/src/main/resources/templates/libraries/microprofile/auth/compositeAuthenticationProvider.qute [hunk 3]
```diff
@@ -1,9 +1,11 @@
 package {apiPackage}.auth;
 
 @jakarta.annotation.Priority(jakarta.ws.rs.Priorities.AUTHENTICATION)
-{#for auth in oauthMethods.orEmpty}
-@io.quarkiverse.openapi.generator.markers.OauthAuthenticationMarker(name="{auth.name}", openApiSpecId="{configKey}")
+{#if oauthMethods.orEmpty.size > 0}
```
Comment (fjtirado) [inline client/deployment/src/main/resources/templates/libraries/microprofile/auth/compositeAuthenticationProvider.qute:4]: If this check really needed having into account that now we are removing duplicates?

**Review by fjtirado — APPROVED** [review]
Just a few nitpicks

File: client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/OpenApiNamespaceResolver.java (hunk 1 above)
Comment (ricardozanini) [reply client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/OpenApiNamespaceResolver.java:77]: It must be an arraylist. Qute looks for the specific arg.

File: client/deployment/src/main/resources/templates/libraries/microprofile/auth/compositeAuthenticationProvider.qute (hunk 3 above)
Comment (ricardozanini) [reply client/deployment/src/main/resources/templates/libraries/microprofile/auth/compositeAuthenticationProvider.qute:4]: Unfortunately, we can't. `oauthMethods` not always is injected in the Qute template context by the underlying openapi-generator. In this cases, an exception would be thrown.

File: client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/OpenApiNamespaceResolver.java (hunk 2 above)
Comment (ricardozanini) [reply client/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/OpenApiNamespaceResolver.java:84]: I don't do oneliners, but I'll change to the `ArrayList`constructor.

**Review by hbelmiro — APPROVED** [review]
