### PR TITLE
Fix #28 - Add Enum Outer Class template and values cache

### LINKED ISSUE #28: Wrong class generated for enum
Ginevn the follwogin OpenApi scheme:

```yaml
   ConnectorNamespaceState:
      type: string
      enum:
        - disconnected
        - ready
        - deleting
```

the extension generates an invalid class:

```java
@JsonIgnoreProperties(ignoreUnknown = true)
public enum ConnectorNamespaceState {
    private String value;

    ConnectorNamespaceState(String value){
        this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static ConnectorNamespaceState fromValue(String text) {
        for (ConnectorNamespaceState b : ConnectorNamespaceState.values()) {
            if (String.valueOf(b.value).equals(text)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }
}
````

Which is wrong as it does not include the listed enum values.

As an additional note, `ConnectorNamespaceState.values()` should probably be cached as each call to `values()` creates a copy of the enum values for each invocation

### PR DESCRIPTION
**Pull request by ricardozanini**
See #28

### CODE REVIEW

**Comment by ricardozanini** [comment]
Fixes #28

File: deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java [hunk 1]
```diff
@@ -47,12 +43,9 @@ public boolean trigger(CodeGenContext context) throws CodeGenException {
...
                             final String basePackage = context.config()
                                     .getOptionalValue(getResolvedBasePackageProperty(openApiFilePath), String.class)
-                                    .orElse(DEFAULT_PACKAGE);
+                                    .orElse("");
                             final OpenApiClientGeneratorWrapper generator = new OpenApiClientGeneratorWrapper(
-                                    openApiFilePath.normalize(), outDir)
-                                            .withApiPackage(basePackage + API_PKG_SUFFIX)
-                                            .withModelPackage(basePackage + MODEL_PKG_SUFFIX)
-                                            .withBasePackage(basePackage);
+                                    openApiFilePath.normalize(), outDir).withBasePackage(basePackage);
```
Comment (fjtirado) [inline deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java:48]: How about writing the same behaviour this way
```
 final OpenApiClientGeneratorWrapper generator = new OpenApiClientGeneratorWrapper(openApiFilePath.normalize(), outDir));
context.config().getOptionalValue(getResolvedBasePackageProperty(openApiFilePath), String.class).map(generator::withBasePackage); 

```

**Review by fjtirado — APPROVED** [review]
