### PR TITLE
Fix #1156 - Move AuthProviders SyntheticBean generation to Runtime

### LINKED ISSUE #1156: Custom CredentialProvider class not loaded
### Tell us the extension you're using

Client

### I tried this:

I am using the version based on my PR https://github.com/quarkiverse/quarkus-openapi-generator/pull/1126 

In my application that uses the openapi-generator dependency, I create a new class that is extending the default credential provider `ConfigCredentialProvider` and I set a higher priority:
```
@RequestScoped
@Alternative
@Specializes
@Priority(10)
public class OpenApiCustomCredentialProvider extends ConfigCredentialsProvider {
    private static final String CANONICAL_EXCHANGE_TOKEN_PROPERTY_NAME = "sonataflow.security.%s.exchange-token";

    private static final Logger LOGGER = LoggerFactory.getLogger(OpenApiCustomCredentialProvider.class);

    @Override
    public String getApiKey(CredentialsContext input) {
        LOGGER.error("========> getApiKey");
        return super.getApiKey(input);
    }

    @Override
    public String getBasicUsername(CredentialsContext input) {
        LOGGER.error("========> getBasicUsername");
        return super.getBasicUsername(input);
    }

    @Override
    public String getBasicPassword(CredentialsContext input) {
        LOGGER.error("========> getBasicPassword");
        return super.getBasicPassword(input);
    }

    @Override
    public String getBearerToken(CredentialsContext input) {
        LOGGER.error("========> getBearerToken");
        return super.getBearerToken(input);
    }

    @Override
    public String getOauth2BearerToken(CredentialsContext input) {
        LOGGER.error("========> getOauth2BearerToken");
       // something intersing
        ...
        return super.getOauth2BearerToken(input);
    }
```

Then I run my integration test that sends a request to a mocked server using OAUTH2 security scheme so I can check if the authorization header is what it should be according to my new class.

### This happened:

I see none of the above logs. (This is for demonstration, in reality I am doing something useful here.)

### I expected this:

To see the logs and to see the header is not the one of the default implementation

### Is there a workaround?

_No response_

### How can we try to reproduce the issue?

create a separate application with this class and see if the class is loaded and if its methods are used in place of the default provider.

### Anything else?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### Quarkus OpenApi version or git rev

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

My repo reproducing the issue: https://github.com/gabriel-farache/openapi-generator-issue-credential-provider

You first need to start the simple-server to see the header set by the application

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.name: Bug Report 🐞

### PR DESCRIPTION
**Pull request by ricardozanini**
Many thanks for submitting your Pull Request :heart:!

Fix #1156.

Additionally, now OAuth2 provider also has an injected CredentialsProvider.

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [our code style](CONTRIBUTING.md#code-style)
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] Subject`
- [x] Pull Request contains link to the issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-quarkus2` to backport the original PR to the `quarkus2` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

File: client/integration-tests/override-credential-provider/src/main/java/io/quarkiverse/openapi/generator/it/creds/CustomCredentialsProvider.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+@Alternative
+@Priority(200)
+public class CustomCredentialsProvider extends ConfigCredentialsProvider {
+    private static final Logger LOGGER = LoggerFactory.getLogger(CustomCredentialsProvider.class);
+
+    public static String TOKEN = "FIXED_TEST_TOKEN";
+
+    @Override
+    public String getBearerToken(ClientRequestContext requestContext, String openApiSpecId, String authName) {
+        LOGGER.info("========> getBearerToken");
```
Comment (gabriel-farache) [inline client/integration-tests/override-credential-provider/src/main/java/io/quarkiverse/openapi/generator/it/creds/CustomCredentialsProvider.java:23]: do you want to keep that message? If yes, my suggestion would be to log a message like "getBearerToken from CustomCredentialsProvider" or something similar so it will more be an informative message rather than a debug one

**Comment by gabriel-farache** [comment]
Thx for fixing this!!

Once it is merged on main, I will rebase #1126 to remove redundancies

File: client/integration-tests/override-credential-provider/src/main/java/io/quarkiverse/openapi/generator/it/creds/CustomCredentialsProvider.java (hunk 1 above)
Comment (ricardozanini) [reply client/integration-tests/override-credential-provider/src/main/java/io/quarkiverse/openapi/generator/it/creds/CustomCredentialsProvider.java:23]: Fine, I'll change it 😅

**Review by gmunozfe — APPROVED** [review]
Looks good to me, great work @ricardozanini !
