### PR TITLE
fix: URL Path Parameter Encoding Issue

### LINKED ISSUE #1460: URL Path Parameter Encoding Issue
## Description

When using the Quarkus OpenAPI Generator extension with GitLab API's `project_id` path parameter (which accepts URL-encoded project paths), the extension either:
1. Doesn't encode slashes when passed unencoded values, causing 404 errors
2. Double-encodes already-encoded values, also causing 404 errors

This makes it impossible to use GitLab's project path format (e.g., `mygroup/myproject/backend`) with the generated REST client.

## Problem

GitLab's API accepts `project_id` as either:
- A numeric project ID (e.g., `12345`)
- A URL-encoded project path (e.g., `mygroup%2Fmyproject%2Fbackend` for `mygroup/myproject/backend`)

### Current Behavior

**Scenario 1: Passing unencoded project path**

Workflow input data:
```json
{
  "project_id": "mygroup/myproject/backend"
}
```

Workflow action:
```yaml
- name: "getMergeRequestDetails"
  functionRef:
    refName: getMergeRequest
    arguments:
      project_id: .project_id
      merge_request_iid: 123
```

Expected URL: `/api/v4/projects/mygroup%2Fmyproject%2Fbackend/merge_requests/123`
Actual URL: `/api/v4/projects/mygroup/myproject/backend/merge_requests/123`
Result: **404 Not Found** (GitLab interprets the slashes as path segments)

**Scenario 2: Passing pre-encoded project path**

Workflow input data:
```json
{
  "project_id": "mygroup%2Fmyproject%2Fbackend"
}
```

Workflow action:
```yaml
- name: "getMergeRequestDetails"
  functionRef:
    refName: getMergeRequest
    arguments:
      project_id: .project_id
      merge_request_iid: 123
```

Expected URL: `/api/v4/projects/mygroup%2Fmyproject%2Fbackend/merge_requests/123`
Actual URL: `/api/v4/projects/mygroup%252Fmyproject%252Fbackend/merge_requests/123`
Result: **404 Not Found** (The `%2F` is encoded again to `%252F`, making it unrecognizable)

### Expected Behavior

The OpenAPI Generator should:
1. **Encode special characters in path parameters** (e.g., `/` → `%2F`)
2. **Detect already-encoded values and skip encoding them** (avoid double encoding)

OR provide a configuration option to control encoding behavior per path parameter.

## OpenAPI Specification

Here's the relevant GitLab API spec showing the `project_id` parameter usage:

```yaml
openapi: 3.0.0
info:
  title: GitLab Repository Automation API
  version: 1.0.0
paths:
  /api/v4/projects/{project_id}/merge_requests/{merge_request_iid}:
    get:
      summary: Get merge request details
      operationId: getMergeRequest
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
        - name: merge_request_iid
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '404':
          description: Not Found
```

### PR DESCRIPTION
**Pull request by matheusandre1**
Many thanks for submitting your Pull Request :heart:!

Please make sure that your PR meets the following requirements:

- [X] You have read the [contributors guide](CONTRIBUTING.md)
- [X] Your code is properly formatted according to [our code style](CONTRIBUTING.md#code-style)
- [X] Pull Request title contains the target branch if not targeting main: `[0.9.x] Subject`
- [X] Pull Request contains link to the issue Closes: #1460 
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-quarkus2` to backport the original PR to the `quarkus2` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

File: client/runtime/src/test/java/io/quarkiverse/openapi/generator/providers/PathParamEncodingParamConverterProviderTest.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+        assertSame(converter, provider.getConverter(String.class, String.class, annotations));
+    }
+
+    private Annotation[] encodedPathParamAnnotations() throws Exception {
+        Method method = getClass().getDeclaredMethod("sample", String.class);
+        return method.getParameters()[0].getAnnotations();
+    }
+
+    @SuppressWarnings("unused")
+    private void sample(@EncodedPathParam String value) {
```
[the remark this answers is not in the document]
Comment (ricardozanini) [reply client/runtime/src/test/java/io/quarkiverse/openapi/generator/providers/PathParamEncodingParamConverterProviderTest.java:67]: Please fix this comment :)

**Review by ricardozanini — APPROVED** [review]
LGTM apart from one tiny comment from our bot.

**Comment by ricardozanini** [comment]
@mcruzdev are you going to take a look?

File: client/deployment/src/main/resources/templates/libraries/microprofile/pathParams.qute [hunk 2]
```diff
@@ -1 +1 @@
-{#if param.isPathParam}@io.quarkiverse.openapi.generator.annotations.GeneratedParam("{param.baseName}") @jakarta.ws.rs.PathParam("{param.baseName}"){param.dataType} {param.paramName}{/if}
\ No newline at end of file
+{#if param.isPathParam}@io.quarkiverse.openapi.generator.annotations.GeneratedParam("{param.baseName}"){#if param.dataType == 'String'}{#if param.vendorExtensions.x-multi-segment.or(false)} @io.quarkiverse.openapi.generator.annotations.MultiSegmentPathParam{#else} @io.quarkiverse.openapi.generator.annotations.EncodedPathParam{/if}{/if} @jakarta.ws.rs.PathParam("{param.baseName}"){param.dataType} {param.paramName}{/if}
```
Comment (mcruzdev) [inline client/deployment/src/main/resources/templates/libraries/microprofile/pathParams.qute:1]: ~~the client extension does not rely in `vendorExtensions` (it is different from server apicurio), it would be great if we have a configuration to apply it like others features.~~

Comment (mcruzdev) [reply client/deployment/src/main/resources/templates/libraries/microprofile/pathParams.qute:1]: Additionally, IMHO we do not need to change the method signature when the future property is disabled for this param.

**Review by mcruzdev — CHANGES_REQUESTED** [review]
It looks great @matheusandre1 thanks a lot. I left a few comments, see if makes sense!

Additionally, I would like to have a documentation for this new feature!

File: client/deployment/src/main/resources/templates/libraries/microprofile/pathParams.qute (hunk 2 above)
Comment (mcruzdev) [reply client/deployment/src/main/resources/templates/libraries/microprofile/pathParams.qute:1]: Sorry, @matheusandre1  I see it now (we added it [here](https://github.com/quarkiverse/quarkus-openapi-generator/pull/1566)), anyway we need to be sure that `@io.quarkiverse.openapi.generator.annotations.EncodedPathParam` does not break backward compatibility.

**Comment by ricardozanini** [comment]
@mcruzdev can you have a look?

**Review by mcruzdev — APPROVED** [review]
Thanks @matheusandre1!
